---
title: "Canopy Openness Index Analysis with R"
output: html_document
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Required Packages

```{r}
library(terra)

library(tidyverse)

library(tidyterra)

library(hemispheR)
```

# Data

## Images path  

```{r}
images <- list.files(path = "cropped-images", 
                     pattern = ".png")

images
```

## Visualizing cannopy images through a looping

```{r}
visualizing_canopy <- function(x){ 
  
  x <- paste0("cropped-images/", x)
  
  raster_bi <- terra::rast(x)
  
  ggplots <- ggplot() +
    tidyterra::geom_spatraster_rgb(data = raster_bi) +
    scale_fill_continuous(na.value = "transparent") +
    scale_x_continuous(expand = c(0, 0)) +
    scale_y_continuous(expand = c(0, 0)) 
  
  print(ggplots)
  
}

purrr::walk(images, visualizing_canopy)
```

# Calculating Canopy Openess index

## Visualizing each binarized images  through a looping

```{r, warning = FALSE}
canopy_visualizing <- function(x){ 
  
  path_file <- paste0("cropped-images/", x) 
  
  image_name <- stringr::str_remove(x, ".png")
  
  analy <- stringr::str_glue("Binnarized image for {image_name}") 
  
  file <- path_file  |>
    hemispheR::import_fisheye()  |>
    hemispheR::binarize_fisheye()
  
  ggplt <- ggplot() +
    tidyterra::geom_spatraster(data = file) +
    scale_fill_viridis_c(na.value = "transparent", breaks = seq(0, 1, 1)) +
    scale_x_continuous(expand = c(0, 0)) +
    scale_y_continuous(expand = c(0, 0)) +
    labs(title = analy) +
    theme_bw()
  
  print(ggplt)
  
}

purrr::walk(images, canopy_visualizing)
```

## Calculating opennes Index for each images through a looping

```{r}
canopy_Openess <- function(x){ 
  
  path_file <- paste0("cropped-images/", x)
  
  image_name <- stringr::str_remove(x, ".png")
  
  stringr::str_glue("Cannopy Opennes Index for {image_name}:") |> 
    crayon::green() |> 
    message()
  
  raster <- path_file |>
    hemispheR::import_fisheye() |>
    hemispheR::binarize_fisheye()
  
  values_0 <- raster[raster > 0] |> 
    terra::ncell()
  
  values_all <- raster |> 
    terra::ncell()
  
  result <- values_0 / values_all
  
  print(result)
  
} 

purrr::walk(images, canopy_Openess)
```

